app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l

class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

app/__init__.py
from flask import Flask
from config import Config
from flask_bootstrap import Bootstrap 
from wtforms import Form, StringField, SelectField
from elasticsearch import Elasticsearch


bootstrap = Bootstrap()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    app.elasticsearch = Elasticsearch([app.config['ELASTICSEARCH_URL']]) \
        if app.config['ELASTICSEARCH_URL'] else None
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import g, render_template, current_app, redirect, url_for, flash, request,jsonify
from app.main.forms import SearchForm
from app.main import bp

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Home Page')

@bp.route('/about')
def about():
    return  render_template('about.html', title='About Us')

app/routes.py
from flask import render_template
from app import app
@app.route('/')
@app.route('/index')
@app.route('/about')
def index():
    return render_template('index.html', title='Home Page')

def about():
    return  render_template('about.html', title='About Us')

app/templates/about.html
{% extends "base.html" %}

{% block content %}
    <h1>Made by 3TCV</h1>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - AI{% else %}Welcome to SEMANTIC Web{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">3TCV</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                </ul>
                {#{% if g.search_form %}
                <form class="navbar-form navbar-left" method="get"
                        action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}#}
                <form class="navbar-form navbar-left">
      				<div class="md-form my-0">
        				<input class="form-control" type="text" placeholder="Search" aria-label="Search" size="100">
        				<i class="fas fa-search text-white ml-3" aria-hidden="true"></i>
      				</div>
    			</form>
  				<ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main.about') }}">About Us</a></li>
                </ul>

  			</div>

        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
 
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>SEMANTIC WEB - Cấu trúc dữ liệu và giải thuật</h1>
{% endblock %}